# Generated by Django 6.1.1 on 2026-10-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_professional_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sif_number',
            field=models.CharField(blank=True, help_text='7-digit unique University SIF number (auto-generated if left blank)', max_length=30, null=True, unique=True),
        ),
    ]
