# Generated by Django 6.1.1 on 2026-10-03 19:00

import django.db.models.deletion
import student_leave.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_student_professional_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Emergency Leave', 'Emergency Leave'), ('Personal Leave', 'Personal Leave'), ('Family Function', 'Family Function'), ('Medical Leave', 'Medical Leave'), ('Other', 'Other')], default='Sick Leave', max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('number_of_days', models.PositiveIntegerField(default=1)),
                ('reason', models.TextField()),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='student_leaves/', validators=[student_leave.models.validate_leave_document])),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Faculty Approved', 'Faculty Approved'), ('Faculty Rejected', 'Faculty Rejected'), ('Incharge Approved', 'Incharge Approved'), ('Incharge Rejected', 'Incharge Rejected'), ('Admin Approved', 'Admin Approved'), ('Admin Rejected', 'Admin Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('student_remarks', models.TextField(blank=True)),
                ('faculty_remarks', models.TextField(blank=True)),
                ('incharge_remarks', models.TextField(blank=True)),
                ('admin_remarks', models.TextField(blank=True)),
                ('approved_rejected_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('approved_rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_student_leaves', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Leave Request',
                'verbose_name_plural': 'Student Leave Requests',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentLeaveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('previous_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_history_actions', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='student_leave.studentleaverequest')),
            ],
            options={
                'verbose_name': 'Student Leave History',
                'verbose_name_plural': 'Student Leave Histories',
                'ordering': ['timestamp'],
            },
        ),
    ]
