# Generated by Django 6.1.1 on 2026-10-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_warning_threshold', models.DecimalField(decimal_places=2, default=75.0, help_text='Attendance percentage below which warning is flagged (Safe: >= this value).', max_digits=5)),
                ('attendance_critical_threshold', models.DecimalField(decimal_places=2, default=65.0, help_text='Attendance percentage below which critical shortage is flagged (Critical: < this value).', max_digits=5)),
                ('marks_passing_threshold', models.DecimalField(decimal_places=2, default=40.0, help_text='Marks percentage required to pass a subject.', max_digits=5)),
                ('marks_distinction_threshold', models.DecimalField(decimal_places=2, default=75.0, help_text='Marks percentage considered high-performing / distinction.', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics Setting',
                'verbose_name_plural': 'Analytics Settings',
            },
        ),
    ]
