# Generated by Django 6.1.1 on 2026-09-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_faculty_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
