# Generated by Django 6.1.1 on 2026-10-03 19:20

import django.db.models.deletion
import django.utils.timezone
import placements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_student_professional_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('industry', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('hr_contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('minimum_qualification', models.CharField(blank=True, default='B.Tech / MCA / Any Graduate', max_length=150)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('employment_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Internship', 'Internship'), ('Internship + Full Time', 'Internship + Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract')], default='Full Time', max_length=50)),
                ('job_location', models.CharField(default='Pan India', max_length=150)),
                ('salary_package', models.CharField(help_text='e.g. 7.5 LPA, 12 LPA, 25,000/month', max_length=100)),
                ('salary_lpa', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric CTC in LPA for sorting/stats', max_digits=6, null=True)),
                ('minimum_percentage', models.DecimalField(decimal_places=2, default=60.0, help_text='Minimum academic percentage required', max_digits=5)),
                ('maximum_backlogs', models.PositiveIntegerField(default=0, help_text='Maximum standing backlogs allowed')),
                ('minimum_qualification', models.CharField(blank=True, default='B.Tech / MCA', max_length=150)),
                ('eligible_year', models.PositiveIntegerField(default=4, help_text='Target graduating year (e.g. 3 or 4). Use 0 for all years.')),
                ('application_start_date', models.DateField(default=django.utils.timezone.now)),
                ('application_deadline', models.DateField()),
                ('drive_date', models.DateField()),
                ('drive_location', models.CharField(default='Campus / Virtual', max_length=200)),
                ('vacancies_count', models.PositiveIntegerField(default=5)),
                ('selection_process', models.TextField(default='Aptitude Test -> Technical Interview -> HR Round')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Closed', 'Closed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='placements.company')),
                ('eligible_courses', models.ManyToManyField(blank=True, help_text='Eligible courses/degrees (leave empty for all)', related_name='placement_drives', to='students.course')),
                ('eligible_departments', models.ManyToManyField(blank=True, help_text='Eligible schools/departments (leave empty for all)', related_name='placement_drives', to='students.department')),
            ],
            options={
                'verbose_name': 'Placement Drive',
                'verbose_name_plural': 'Placement Drives',
                'ordering': ['-drive_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(upload_to='placement_resumes/', validators=[placements.models.validate_resume_file])),
                ('cover_letter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Interview Scheduled', 'Interview Scheduled'), ('Selected', 'Selected'), ('Not Selected', 'Not Selected'), ('Withdrawn', 'Withdrawn')], default='Applied', max_length=30)),
                ('eligibility_status', models.BooleanField(default=True)),
                ('current_round', models.CharField(default='Application Review', max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_applications', to='students.student')),
                ('placement_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placements.placementdrive')),
            ],
            options={
                'verbose_name': 'Placement Application',
                'verbose_name_plural': 'Placement Applications',
                'ordering': ['-application_date'],
                'unique_together': {('student', 'placement_drive')},
            },
        ),
        migrations.CreateModel(
            name='PlacementResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('ctc', models.CharField(max_length=100)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('placement_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Internship', 'Internship'), ('Internship + Full Time', 'Internship + Full Time')], default='Full Time', max_length=50)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='placement_offers/', validators=[placements.models.validate_resume_file])),
                ('result', models.CharField(choices=[('Selected', 'Selected'), ('Not Selected', 'Not Selected')], default='Selected', max_length=30)),
                ('result_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_results', to='placements.company')),
                ('placement_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_results', to='placements.placementdrive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_results', to='students.student')),
            ],
            options={
                'verbose_name': 'Placement Result',
                'verbose_name_plural': 'Placement Results',
                'ordering': ['-result_date'],
            },
        ),
        migrations.CreateModel(
            name='PlacementRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('round_name', models.CharField(max_length=100)),
                ('round_type', models.CharField(choices=[('Aptitude', 'Aptitude Test'), ('Technical Test', 'Technical Test'), ('Coding', 'Coding Test'), ('Group Discussion', 'Group Discussion'), ('Technical Interview', 'Technical Interview'), ('HR Interview', 'HR Interview'), ('Final Interview', 'Final Interview'), ('Other', 'Other')], default='Technical Interview', max_length=50)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(default='Room 302 / Online Meet', max_length=200)),
                ('interviewer', models.CharField(blank=True, max_length=150)),
                ('result', models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Selected', 'Selected')], default='Pending', max_length=20)),
                ('score', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='placements.placementapplication')),
            ],
            options={
                'verbose_name': 'Placement Round',
                'verbose_name_plural': 'Placement Rounds',
                'ordering': ['round_number', 'scheduled_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentPlacementProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_resume', models.FileField(blank=True, null=True, upload_to='placement_resumes/', validators=[placements.models.validate_resume_file])),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated skills e.g. Python, SQL, React', max_length=300)),
                ('bio', models.TextField(blank=True)),
                ('cgpa_or_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('active_backlogs', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_profile', to='students.student')),
            ],
        ),
    ]
