# Generated by Django 6.1.1 on 2026-10-04 07:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
        ('students', '0005_student_professional_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostelbed',
            options={'ordering': ['bed_number'], 'verbose_name': 'Hostel Bed', 'verbose_name_plural': 'Hostel Beds'},
        ),
        migrations.AlterModelOptions(
            name='hostelblock',
            options={'ordering': ['name'], 'verbose_name': 'Hostel Block', 'verbose_name_plural': 'Hostel Blocks'},
        ),
        migrations.AlterModelOptions(
            name='hostelfloor',
            options={'ordering': ['floor_number'], 'verbose_name': 'Hostel Floor', 'verbose_name_plural': 'Hostel Floors'},
        ),
        migrations.AlterModelOptions(
            name='hostelroom',
            options={'ordering': ['room_number'], 'verbose_name': 'Hostel Room', 'verbose_name_plural': 'Hostel Rooms'},
        ),
        migrations.CreateModel(
            name='HostelApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('room_type_preference', models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('TRIPLE', 'Triple'), ('FOUR_SHARING', 'Four Sharing'), ('DORMITORY', 'Dormitory'), ('OTHER', 'Other')], default='DOUBLE', max_length=20)),
                ('academic_year', models.CharField(default='2026-27', max_length=20)),
                ('application_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, help_text='Reason for requesting hostel accommodation')),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hostel.hostel', verbose_name='Preferred Hostel')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_hostel_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_applications', to='students.student')),
            ],
            options={
                'verbose_name': 'Hostel Application',
                'verbose_name_plural': 'Hostel Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
