# Generated by Django 6.1.1 on 2026-10-04 07:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_alter_hostelbed_options_alter_hostelblock_options_and_more'),
        ('students', '0005_student_professional_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('allocation_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_checkout_date', models.DateField(blank=True, null=True)),
                ('actual_checkout_date', models.DateField(blank=True, null=True)),
                ('academic_year', models.CharField(default='2026-27', max_length=20)),
                ('semester', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRANSFERRED', 'Transferred'), ('CHECKED_OUT', 'Checked Out'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_hostel_students', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostel.hostelbed')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostel.hostelblock')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostel.hostelfloor')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostel.hostel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostel.hostelroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to='students.student')),
            ],
            options={
                'verbose_name': 'Hostel Allocation',
                'verbose_name_plural': 'Hostel Allocations',
                'ordering': ['-allocation_date', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student',), name='unique_active_student_hostel_allocation'), models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('bed',), name='unique_active_bed_hostel_allocation')],
            },
        ),
    ]
