# Generated by Django 6.1.1 on 2026-10-04 07:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_hostelcheckinout'),
        ('students', '0005_student_professional_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelRoomTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField(help_text='Reason for room/bed transfer request')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='hostel.hostelallocation')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hostel_transfers', to=settings.AUTH_USER_MODEL)),
                ('new_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='hostel.hostelbed')),
                ('new_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='hostel.hostelblock')),
                ('new_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='hostel.hostelfloor')),
                ('new_hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='hostel.hostel')),
                ('new_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='hostel.hostelroom')),
                ('old_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='hostel.hostelbed')),
                ('old_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='hostel.hostelblock')),
                ('old_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='hostel.hostelfloor')),
                ('old_hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='hostel.hostel')),
                ('old_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='hostel.hostelroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_transfers', to='students.student')),
            ],
            options={
                'verbose_name': 'Hostel Room Transfer',
                'verbose_name_plural': 'Hostel Room Transfers',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
    ]
