# Generated by Django 6.1.1 on 2026-10-04 08:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_hostelroomtransfer'),
        ('students', '0005_student_professional_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('PERMISSION', 'Permission'), ('LEAVE', 'Leave')], default='PRESENT', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hostel.hostel')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_hostel_attendances', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='hostel.hostelroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_attendances', to='students.student')),
            ],
            options={
                'verbose_name': 'Hostel Attendance',
                'verbose_name_plural': 'Hostel Attendances',
                'ordering': ['-date', 'student__name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='unique_student_date_hostel_attendance')],
            },
        ),
    ]
