# Generated by Django 6.1.1 on 2026-10-04 08:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_hostelcomplaint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANT', 'Important'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='hostel/notices/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_hostel_notices', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='hostel.hostel')),
            ],
            options={
                'verbose_name': 'Hostel Notice',
                'verbose_name_plural': 'Hostel Notices',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelWarden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CHIEF_WARDEN', 'Chief Warden'), ('WARDEN', 'Hostel Warden'), ('ASSISTANT_WARDEN', 'Assistant Warden'), ('CARETAKER', 'Hostel Caretaker')], default='WARDEN', max_length=30)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warden_assignments', to='hostel.hostel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_warden_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hostel Warden Assignment',
                'verbose_name_plural': 'Hostel Warden Assignments',
                'ordering': ['hostel__name', 'role'],
                'constraints': [models.UniqueConstraint(fields=('hostel', 'user'), name='unique_hostel_warden_assignment')],
            },
        ),
    ]
