# Generated by Django 6.1.1 on 2026-10-04 05:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_student_professional_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(help_text='Unique identifier e.g. BONAFIDE', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description and instructions for students')),
                ('requires_approval', models.BooleanField(default=True, help_text='Whether this certificate requires staff/admin approval before generation')),
                ('is_pdf_available', models.BooleanField(default=True, help_text='Whether automatic PDF generation is enabled for this certificate')),
                ('is_active', models.BooleanField(default=True, help_text='Whether students can request this certificate')),
                ('template_content', models.TextField(blank=True, help_text='Custom wording template. Supports {student_name}, {roll_no}, {course_name}, {department_name}, {year}, {purpose}, {sif_number}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate Type',
                'verbose_name_plural': 'Certificate Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, help_text='Unique Request Identifier (e.g. CERT-REQ-2026-000001)', max_length=32, unique=True)),
                ('purpose', models.CharField(help_text='Reason/purpose for requesting certificate', max_length=255)),
                ('additional_remarks', models.TextField(blank=True, help_text='Optional remarks or notes from student')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Generated', 'Generated'), ('Downloaded', 'Downloaded')], db_index=True, default='Pending', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, help_text='Mandatory reason if request is rejected')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_certificate_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to='students.student')),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='certificates.certificatetype')),
            ],
            options={
                'verbose_name': 'Certificate Request',
                'verbose_name_plural': 'Certificate Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(db_index=True, help_text='Unique Certificate Number (e.g. SC-CERT-2026-000001)', max_length=50, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('signatory_title', models.CharField(default='Principal / Academic Registrar', max_length=120)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/generated/%Y/%m/')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_certificates', to='certificates.certificatetype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certificates', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_certificate', to='certificates.certificaterequest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_certificates', to='students.student')),
            ],
            options={
                'verbose_name': 'Generated Certificate',
                'verbose_name_plural': 'Generated Certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID Proof', 'ID Proof'), ('Address Proof', 'Address Proof'), ('Previous Marksheet', 'Previous Marksheet'), ('Transfer Certificate', 'Transfer Certificate'), ('Community Certificate', 'Community Certificate'), ('Internship Certificate', 'Internship Certificate'), ('Other Document', 'Other Document')], default='Other Document', max_length=50)),
                ('title', models.CharField(help_text='Descriptive title of document', max_length=150)),
                ('file', models.FileField(upload_to='documents/student_docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('Pending Verification', 'Pending Verification'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], db_index=True, default='Pending Verification', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason if document verification was rejected')),
                ('remarks', models.TextField(blank=True, help_text='Notes/remarks from student or staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_student_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_student_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Document',
                'verbose_name_plural': 'Student Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='certificaterequest',
            index=models.Index(fields=['status', 'student'], name='certificate_status_674df8_idx'),
        ),
        migrations.AddIndex(
            model_name='certificaterequest',
            index=models.Index(fields=['created_at'], name='certificate_created_1792b3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['student', 'verification_status'], name='certificate_student_0723b2_idx'),
        ),
    ]
