# Generated by Django 6.1.1 on 2026-10-03 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('faculty', '0005_faculty_profile_subject_academic'),
        ('students', '0005_student_professional_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='room_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='Room Number'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20, verbose_name='Exam Status'),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exams.exam', verbose_name='Exam'),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='faculty.subject', verbose_name='Subject'),
        ),
        migrations.CreateModel(
            name='StudentExamMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.PositiveIntegerField(default=100, verbose_name='Maximum Marks')),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Marks Obtained')),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentage')),
                ('grade', models.CharField(blank=True, max_length=5, verbose_name='Grade')),
                ('grade_point', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Grade Point')),
                ('result_status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Absent', 'Absent')], default='Pass', max_length=15, verbose_name='Result Status')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_exam_marks', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='exams.exam', verbose_name='Exam')),
                ('exam_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks', to='exams.examschedule', verbose_name='Exam Schedule Slot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='students.student', verbose_name='Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='faculty.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Student Exam Mark',
                'verbose_name_plural': 'Student Exam Marks',
                'ordering': ['-exam__start_date', 'subject__name', 'student__roll_no'],
                'constraints': [models.UniqueConstraint(fields=('student', 'exam', 'subject'), name='unique_student_exam_subject_mark')],
            },
        ),
    ]
