from django.urls import path
from . import views
from . import reports

app_name = "hostel"

urlpatterns = [
    path("", views.HostelHomeView.as_view(), name="home"),
    path("dashboard/", views.HostelAdminDashboardView.as_view(), name="admin_dashboard"),
    path("admin/dashboard/", views.HostelAdminDashboardView.as_view(), name="admin_dashboard_alt"),
    path("rooms/", views.HostelRoomSearchView.as_view(), name="room_search"),
    path("admin/rooms/", views.HostelRoomSearchView.as_view(), name="admin_room_search"),
    path("portal/", views.HostelHomeView.as_view(), name="student_portal"),
    path("applications/", views.ApplicationListView.as_view(), name="application_list"),
    path("applications/create/", views.ApplicationCreateView.as_view(), name="application_create"),
    path("applications/<int:pk>/", views.ApplicationDetailView.as_view(), name="application_detail"),
    path("admin/applications/", views.AdminApplicationListView.as_view(), name="admin_applications"),
    path("admin/applications/<int:pk>/review/", views.AdminApplicationReviewView.as_view(), name="admin_application_review"),
    path("admin/allocations/", views.AdminAllocationListView.as_view(), name="admin_allocations"),
    path("admin/allocations/create/", views.AdminAllocationCreateView.as_view(), name="admin_allocation_create"),
    path("admin/allocations/<int:pk>/", views.AdminAllocationDetailView.as_view(), name="admin_allocation_detail"),
    path("admin/allocations/<int:pk>/event/", views.ProcessCheckInOutView.as_view(), name="admin_allocation_event"),
    path("admin/allocations/<int:pk>/transfer/", views.AdminRoomTransferView.as_view(), name="admin_allocation_transfer"),
    path("fees/", views.StudentHostelFeeView.as_view(), name="student_fees"),
    path("admin/fees/", views.AdminHostelFeeListView.as_view(), name="admin_fees"),
    path("admin/fees/create/", views.AdminCreateHostelFeeView.as_view(), name="admin_fee_create"),
    path("admin/fees/<int:fee_id>/pay/", views.AdminRecordHostelPaymentView.as_view(), name="admin_fee_pay"),
    path("attendance/", views.StudentHostelAttendanceView.as_view(), name="student_attendance"),
    path("admin/attendance/", views.AdminHostelAttendanceView.as_view(), name="admin_attendance"),
    path("complaints/", views.StudentComplaintListView.as_view(), name="student_complaint_list"),
    path("complaints/list/", views.StudentComplaintListView.as_view(), name="student_complaints"),
    path("complaints/create/", views.StudentComplaintCreateView.as_view(), name="student_complaint_create"),
    path("complaints/<int:pk>/", views.StudentComplaintDetailView.as_view(), name="student_complaint_detail"),
    path("admin/complaints/", views.AdminComplaintListView.as_view(), name="admin_complaints"),
    path("admin/complaints/<int:pk>/", views.AdminComplaintDetailView.as_view(), name="admin_complaint_detail"),
    path("notices/", views.StudentHostelNoticeListView.as_view(), name="student_notices"),
    path("admin/notices/", views.AdminHostelNoticeListView.as_view(), name="admin_notices"),
    path("admin/notices/create/", views.AdminCreateHostelNoticeView.as_view(), name="admin_notice_create"),
    path("visitors/", views.StudentVisitorListView.as_view(), name="student_visitors"),
    path("visitors/create/", views.StudentVisitorCreateView.as_view(), name="student_visitor_create"),
    path("admin/visitors/", views.AdminVisitorListView.as_view(), name="admin_visitors"),
    path("admin/visitors/<int:pk>/", views.AdminVisitorUpdateView.as_view(), name="admin_visitor_update"),
    # Phase 14: Reports & Exports
    path("admin/reports/", reports.HostelReportsHubView.as_view(), name="admin_reports_hub"),
    path("admin/reports/occupancy/excel/", reports.ExportHostelOccupancyExcelView.as_view(), name="export_occupancy_excel"),
    path("admin/reports/occupancy/pdf/", reports.ExportHostelOccupancyPdfView.as_view(), name="export_occupancy_pdf"),
    path("admin/reports/allocations/excel/", reports.ExportHostelAllocationsExcelView.as_view(), name="export_allocations_excel"),
    path("admin/reports/allocations/pdf/", reports.ExportHostelAllocationsPdfView.as_view(), name="export_allocations_pdf"),
    path("admin/reports/availability/excel/", reports.ExportHostelAvailabilityExcelView.as_view(), name="export_availability_excel"),
    path("admin/reports/availability/pdf/", reports.ExportHostelAvailabilityPdfView.as_view(), name="export_availability_pdf"),
    path("admin/reports/attendance/excel/", reports.ExportHostelAttendanceExcelView.as_view(), name="export_attendance_excel"),
    path("admin/reports/attendance/pdf/", reports.ExportHostelAttendancePdfView.as_view(), name="export_attendance_pdf"),
    path("admin/reports/fees/excel/", reports.ExportHostelFeesExcelView.as_view(), name="export_fees_excel"),
    path("admin/reports/fees/pdf/", reports.ExportHostelFeesPdfView.as_view(), name="export_fees_pdf"),
    path("admin/reports/complaints/excel/", reports.ExportHostelComplaintsExcelView.as_view(), name="export_complaints_excel"),
    path("admin/reports/complaints/pdf/", reports.ExportHostelComplaintsPdfView.as_view(), name="export_complaints_pdf"),
    path("admin/reports/applications/excel/", reports.ExportHostelApplicationsExcelView.as_view(), name="export_applications_excel"),
    path("admin/reports/applications/pdf/", reports.ExportHostelApplicationsPdfView.as_view(), name="export_applications_pdf"),
    path("admin/reports/checkinout/excel/", reports.ExportHostelCheckInOutExcelView.as_view(), name="export_checkinout_excel"),
    path("admin/reports/checkinout/pdf/", reports.ExportHostelCheckInOutPdfView.as_view(), name="export_checkinout_pdf"),
    path("admin/reports/transfers/excel/", reports.ExportHostelTransfersExcelView.as_view(), name="export_transfers_excel"),
    path("admin/reports/transfers/pdf/", reports.ExportHostelTransfersPdfView.as_view(), name="export_transfers_pdf"),
    path("admin/reports/visitors/excel/", reports.ExportHostelVisitorsExcelView.as_view(), name="export_visitors_excel"),
    path("admin/reports/visitors/pdf/", reports.ExportHostelVisitorsPdfView.as_view(), name="export_visitors_pdf"),
]

