# Generated by Django 6.1.1 on 2026-10-03 18:01

import assignments.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0005_faculty_profile_subject_academic'),
        ('students', '0005_student_professional_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Assignment Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('year', models.PositiveSmallIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], verbose_name='Year')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], verbose_name='Semester')),
                ('academic_year', models.CharField(default='2026-2027', max_length=20, verbose_name='Academic Year')),
                ('assignment_type', models.CharField(choices=[('Assignment', 'Assignment'), ('Homework', 'Homework'), ('Project', 'Project'), ('Lab Record', 'Lab Record'), ('Seminar', 'Seminar'), ('Case Study', 'Case Study')], default='Assignment', max_length=50, verbose_name='Assignment Type')),
                ('assigned_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Assigned Date')),
                ('submission_deadline', models.DateTimeField(verbose_name='Submission Deadline')),
                ('max_marks', models.PositiveIntegerField(default=100, verbose_name='Maximum Marks')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/materials/%Y/%m/', validators=[assignments.models.validate_file_size, assignments.models.validate_allowed_file_extension], verbose_name='Attachment / Material File')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='students.course', verbose_name='Course/Degree')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to='faculty.faculty', verbose_name='Faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='faculty.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-submission_deadline', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(upload_to='assignments/submissions/%Y/%m/', validators=[assignments.models.validate_file_size, assignments.models.validate_allowed_file_extension], verbose_name='Submission File')),
                ('student_remarks', models.TextField(blank=True, verbose_name='Student Remarks')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('Not Submitted', 'Not Submitted'), ('Submitted', 'Submitted'), ('Late', 'Late'), ('Evaluated', 'Evaluated'), ('Returned', 'Returned')], default='Submitted', max_length=30, verbose_name='Submission Status')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Marks Obtained')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentage')),
                ('feedback', models.TextField(blank=True, verbose_name='Faculty Feedback')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='Evaluation Date')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='Assignment')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Evaluated By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Assignment Submission',
                'verbose_name_plural': 'Assignment Submissions',
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'student'), name='unique_assignment_student_submission')],
            },
        ),
    ]
