from decimal import Decimal

from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet

from faculty.models import Faculty
from students.models import Student

from .models import FeePayment, FeeRecord


def _student_for_request(request):
    return Student.objects.filter(user=request.user).select_related(
        "department", "course"
    ).first()


@login_required(login_url="/accounts/login/")
def fee_dashboard(request):
    student = _student_for_request(request)

    if request.user.is_superuser:
        records = list(
            FeeRecord.objects.select_related("student", "student__course")
            .prefetch_related("payments")
            .order_by("-created_at")
        )
    elif student:
        records = list(
            FeeRecord.objects.filter(student=student)
            .prefetch_related("payments")
            .order_by("-created_at")
        )
    else:
        # Faculty accounts do not get access to fee data by default.
        if Faculty.objects.filter(user=request.user).exists() or Faculty.objects.filter(email=request.user.email).exists():
            raise PermissionDenied
        records = []

    total_fee = sum((record.amount for record in records), Decimal("0.00"))
    total_paid = sum((record.paid_amount for record in records), Decimal("0.00"))
    total_balance = max(total_fee - total_paid, Decimal("0.00"))

    payments = []
    for record in records:
        for payment in record.payments.all():
            payments.append(payment)
    payments.sort(key=lambda payment: (payment.payment_date, payment.created_at), reverse=True)

    context = {
        "student": student,
        "records": records,
        "payments": payments[:15],
        "total_fee": total_fee,
        "total_paid": total_paid,
        "total_balance": total_balance,
        "record_count": len(records),
    }
    return render(request, "fees/dashboard.html", context)


@login_required(login_url="/accounts/login/")
def payment_receipt(request, payment_id):
    payment = get_object_or_404(
        FeePayment.objects.select_related(
            "fee_record", "fee_record__student", "fee_record__student__course",
            "fee_record__student__department",
        ),
        pk=payment_id,
    )

    student = _student_for_request(request)
    if not request.user.is_superuser:
        if student is None or payment.fee_record.student_id != student.id:
            raise PermissionDenied

    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = f'inline; filename="receipt-{payment.receipt_number}.pdf"'

    document = SimpleDocTemplate(
        response, pagesize=A4, rightMargin=42, leftMargin=42, topMargin=42, bottomMargin=42
    )
    styles = getSampleStyleSheet()
    elements = [
        Paragraph("SMART COLLEGE", styles["Title"]),
        Paragraph("Official Fee Payment Receipt", styles["Heading2"]),
        Spacer(1, 18),
    ]

    record = payment.fee_record
    student_obj = record.student
    data = [
        ["Receipt Number", payment.receipt_number],
        ["Payment Date", payment.payment_date.strftime("%d %b %Y")],
        ["Student", student_obj.name],
        ["Roll Number", student_obj.roll_no],
        ["Degree / Course", str(student_obj.course) if student_obj.course else "—"],
        ["Fee", record.title],
        ["Academic Year", record.academic_year],
        ["Payment Mode", payment.get_payment_mode_display()],
        ["Reference Number", payment.reference_number or "—"],
        ["Amount Paid", f"₹{payment.amount:,.2f}"],
    ]
    table = Table(data, colWidths=[145, 330])
    table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f3f4f6")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 24))
    elements.append(Paragraph("This receipt is generated by the Smart College ERP system.", styles["Normal"]))

    document.build(elements)
    return response
