# Generated by Django 6.1.1 on 2026-09-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='internal_1',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='internal_2',
        ),
        migrations.AddField(
            model_name='marks',
            name='cat_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='cat_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='cat_3',
            field=models.IntegerField(default=0),
        ),
    ]
