# Generated by Django 6.1.1 on 2026-09-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_subject'),
        ('marks', '0002_remove_marks_assignment_remove_marks_internal_1_and_more'),
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='marks',
            constraint=models.UniqueConstraint(fields=('student', 'subject'), name='unique_student_subject_marks'),
        ),
    ]
