# Generated by Django 6.1.1 on 2026-09-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('faculty', '0002_subject'),
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'date'), name='unique_student_subject_date'),
        ),
    ]
