# Generated by Django 6.1.1 on 2026-09-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_unique_student_subject_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_student_subject_date',
        ),
    ]
