# Generated by Django 6.1.1 on 2026-09-27 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendance_unique_student_subject_date'),
        ('faculty', '0004_faculty_is_approved'),
        ('students', '0004_student_sif_number_course_student_course'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.period'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'date', 'period'), name='unique_student_subject_date_period'),
        ),
    ]
